apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-stage-v2
  namespace: argocd
spec:
  destination:
    namespace: microservices-stage
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-stage.yaml
    path: helm/api
    repoURL: https://github.com/Raptorex65/multi-cloud-platform-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: LogicalID:
        Type: AWS::Route53Resolver::FirewallRuleGroupAssociation
        Properties:
          FirewallRuleGroupId: "String" # Required
          MutationProtection: "String"
          Name: "String"
          Priority: "Number" # Required
          Tags: 
            - Key: "String"
              Value: "String"
          VpcId: "String" # Required
    syncOptions:
      - CreateNamespace=true