apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-prod-v2
  namespace: argocd
spec:
  destination:
    namespace: microservices-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: helm/frontend
    repoURL: https://github.com/Raptorex65/multi-cloud-platform-gitops.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true