apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault-store
spec:
  provider:
    azurekv:
      tenantId: "df65a098-823f-4583-8c96-9257fce32c1d"
      vaultUrl: "https://mc-platform-dev-kv.vault.azure.net/"
      authType: WorkloadIdentity
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
      clientID: "52820662-8c58-4651-a4b5-eba3cac72582"