apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-azure-prod-v2
  namespace: argocd
spec:
  destination:
    namespace: microservices-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/apps/microservices-platform/azure/dev
    repoURL: https://github.com/Raptorex65/multi-cloud-platform-gitops.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true