apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-ingress
  namespace: microservices-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: dev.4.231.82.88.nip.io  
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-stable-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-dev-azure-v2-frontend
                port:
                  number: 80