apiVersion: v1
kind: Service
metadata:
  name: api-stable-service
spec:
  selector:
    app: {{ include "api.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: api-canary-service
spec:
  selector:
    app: {{ include "api.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  type: ClusterIP

  # For initial phases normally we had one api-service,
  # To implement real traffic-splitting canary for argo rollout sliced it into two new services named api-stable-service and api-canary-service. 