apiVersion: apps/v1
kind: Deployment
metadata:
 name: api-deploy
spec:
 replicas: {{ .Values.replicaCount }}
 selector: 
  matchLabels:
   app: {{ include "api.fullname" . }}
 template:
  metadata:
   labels:
    app: {{ include "api.fullname" . }}
  spec:
   containers:
    - name: {{ include "api.fullname" . }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: IfNotPresent
      ports:
       - containerPort: {{ .Values.service.targetPort }}      